### ISSUE TITLE
Add OneDrive

### ISSUE THREAD

**Issue by burningscript** [MangoCubes/cryptomator-web#3]
Hello, is it possible to add OneDrive?

**Comment by MangoCubes** [comment]
I'll try, but I cannot guarantee it, since I have never used OneDrive before. However, there is a library that seems to do what I need (onedrive-api), and hopefully it can be abstracted.

**Comment by burningscript** [comment]
That would be really cool! Sadly I dont know Typescript ans therefore I am not able to do this by myself

Von meinem iPhone gesendet

Am 09.05.2023 um 18:09 schrieb MangoCubes ***@***.***>:

﻿

I'll try, but I cannot guarantee it, since I have never used OneDrive before. However, there is a library that seems to do what I need (onedrive-api), and hopefully it can be abstracted.

**Comment by MangoCubes** [comment]
Okay, so after a bit of trial and error, I finally got how the hell Microsoft login works. Additionally, the library I found seems to not work with browser for some reason (not to mention the lack of typing), so I have to implement all that myself. Sorry, it might take more than expected. But I have successfully managed to get getting item list working, and I only need to add OneDrive class for this to work.

**Comment by MangoCubes** [comment]
Okay. So I've done some basic testing and it seems to be working. Can you test it here?

https://mangocubes.github.io/cryptomator-web/

To login, press the "Use OneDrive Instead", and log in to your Microsoft account. It works only with personal accounts for now. Do let me know of the bugs, though I haven't done extensive debugging yet. That, and whether you managed to log in at once. It originally happened, but I cannot reproduce it anymore, and I have no idea whether it's fixed or it just doesn't happen with my account anymore or something like that.
